org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=1.21.11
loader_version=0.19.5
loom_version=1.17-SNAPSHOT

version=1.0.0
group=com.baton

fabric_api_version=0.141.6+1.21.11
netty_version=4.2.7.Final
sodium_version=rkdTcxoT
lithium_version=Ow7wA0kG
ferritecore_version=Ii0gP3D8
immediatelyfast_version=4EwhsTu7
entityculling_version=CFBkR8Vm
